### ISSUE TITLE
Please switch from setup-ghdl-ci to setup-ghdl

### ISSUE THREAD

**Issue by Paebbels** [enjoy-digital/litex#2156]
> [!CAUTION]
> This GitHub Action (`setup-ghdl-ci`) has been **deprecated** in favor of the new [setup-ghdl](https://github.com/ghdl/setup-ghdl) Action.
> Please update your YAML files and transition to the new GitHub Action. See the linked repository for details on optional parameters.

**Quick example:**
```yml
jobs:
  GHDL-on-Ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: Run VHDL Simulation
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: mcode
```

**Why has it been changed?**  
* The Javascript GitHub Action is hard to maintain.  
  In addition, it has a high complexity with Node.js and other tools compare to a much simpler Composite Action using simple shell instructions in Bash/Powershell.
* This action doesn't support the `ubuntu-24.04` (= `ubuntu-latest`) runner image.
* This Action uses wrong tagging to select GHDL versions. See analysis: https://github.com/ghdl/ghdl/issues/2852
* Due to changes in GHDL's nightly releases and attached assets, the filenames are broken.

-----------------------
This repository has been listed by [Dependabot](https://github.com/ghdl/setup-ghdl-ci/network/dependents) as a dependent of `setup-ghdl-ci`.
